// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLRFa6GjWFMSPt1f6AmiM3XXSJw-O3isQ',
    appId: '1:118632789771:web:54a8af2924bc87ccc2d40e',
    messagingSenderId: '118632789771',
    projectId: 'e-spirit-care',
    authDomain: 'e-spirit-care.firebaseapp.com',
    storageBucket: 'e-spirit-care.firebasestorage.app',
    measurementId: 'G-B7S14NFE1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9bhPyZYFI-kS5qzMvMMXCQ83yU4EcoRA',
    appId: '1:118632789771:android:a7d2a130c0bccfd4c2d40e',
    messagingSenderId: '118632789771',
    projectId: 'e-spirit-care',
    storageBucket: 'e-spirit-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37RMyLR9lmoCocdc95lVtPBUmNMx53wE',
    appId: '1:118632789771:ios:320aa438e6bbfcc0c2d40e',
    messagingSenderId: '118632789771',
    projectId: 'e-spirit-care',
    storageBucket: 'e-spirit-care.firebasestorage.app',
    iosBundleId: 'com.gloriyan.eSpiritCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37RMyLR9lmoCocdc95lVtPBUmNMx53wE',
    appId: '1:118632789771:ios:320aa438e6bbfcc0c2d40e',
    messagingSenderId: '118632789771',
    projectId: 'e-spirit-care',
    storageBucket: 'e-spirit-care.firebasestorage.app',
    iosBundleId: 'com.gloriyan.eSpiritCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLRFa6GjWFMSPt1f6AmiM3XXSJw-O3isQ',
    appId: '1:118632789771:web:79329d80c225cbd8c2d40e',
    messagingSenderId: '118632789771',
    projectId: 'e-spirit-care',
    authDomain: 'e-spirit-care.firebaseapp.com',
    storageBucket: 'e-spirit-care.firebasestorage.app',
    measurementId: 'G-QLMLC4S28B',
  );
}
